version: "3.9"

volumes:
  dbdata:
  redis:
  meilisearch:

services:
  db:
    image: "postgres:latest"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - './db_dump:/db_dump'
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/meili-data
  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_URL: redis://redis:6379
      MEILISEARCH_HOST: 'meilisearch:7700'
      MEILISEARCH_API_KEY: 'meilikey'
    volumes:
      - .:/myapp
  sidekiq:
    build: .
    restart: always
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/myapp
    env_file: .env
    environment:
      # RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/postgres
      REDIS_URL: redis://redis:6379
      MEILISEARCH_HOST: 'meilisearch:7700'
      MEILISEARCH_API_KEY: 'meilikey'

