version: "3.9"

services:
  db:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
    networks:
      - backend

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - "7700:7700"
    volumes:
      - meilisearch:/meili-data
    networks:
      - backend

  web:
    build: .
    restart: always
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
      - redis
      - meilisearch
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/myapp
    networks:
      - backend
    tmpfs:
      - /myapp/tmp/pids

  sidekiq:
    build: .
    restart: always
    command: bash -c "bundle exec sidekiq"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/postgres
      - REDIS_URL=redis://redis:6379
    networks:
      - backend

volumes:
  dbdata:
  redis:
  meilisearch:

networks:
  backend:
    driver: "bridge"
