services:
  - type: web
    name: tangotube-web
    region: frankfurt
    plan: starter plus
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: export PATH="$PATH:$HOME/project/src/yt-dlp"; bundle exec puma -C config/puma.rb
    domains:
      - tangotube.tv
    disk:
      name: data
      mountPath: /var/lib/data
      sizeGB: 5
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: tangotube-redis
          type: redis
          property: connectionString
      - fromGroup: tangotube-environment-group

  - type: worker
    name: tangotube-sidekiq
    region: frankfurt
    plan: Starter Plus
    env: ruby
    buildCommand: ./bin/render-build.sh
    startCommand: export PATH="$PATH:$HOME/project/src/yt-dlp"; bundle exec sidekiq -e production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tangotube-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: tangotube-redis
          type: redis
          property: connectionString
      - fromGroup: tangotube-environment-group

  - name: tangotube-redis
    type: redis
    plan: starter
    region: frankfurt
    ipAllowList:
      - source: "0.0.0.0/0"
        description: home
    maxmemoryPolicy: no-eviction

databases:
  - name: tangotube-db
    plan: standard
    region: frankfurt
    ipAllowList:
      - source: "0.0.0.0/0"
        description: home

envVarGroups:
  - name: tangotube-environment-group
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
