development:
  :concurrency: 20
  :timeout: 500  
production:
  :concurrency: <%= ENV["SIDEKIQ_CONCURRENCY_VALUE"] || 10 %>
  :timeout: 10
:queues:
  - high
  - mailers
  - default
  - ahoy

:schedule:
  hello_world:
    cron: '0 * * * * *'   # Runs once per minute
    class: HelloWorld